<a href="https://colab.research.google.com/github/VidushiHub/AI-Powered-Workforce-Analytics-Talent-Intelligence-Dashboard/blob/main/SQL_Prompt_Ececution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Student Management System with SQLite

Create a Student Management System. Requirements: 1. Create two tables: Students and Courses. 2. Insert at least 5 records into each table. 3. Perform the following DDL operations: - CREATE TABLE - ALTER TABLE 4. Perform the following DML operations: - INSERT - UPDATE - DELETE 5. Write SQL queries using: - SELECT - WHERE - ORDER BY - GROUP BY - COUNT - AVG 6. Perform an INNER JOIN between the Students and Courses tables. 7. Add comments to explain each step. 8. Display the output of each query. 9. Ensure the code runs successfully in Google Colab using SQLite.

In [8]:
import sqlite3
import pandas as pd

# Connect to an in-memory SQLite database
# This database will be cleared when the Colab runtime restarts
conn = sqlite3.connect(':memory:')
c = conn.cursor()

print("SQLite database connected successfully in memory.")

SQLite database connected successfully in memory.

### 1. Create Tables: Students and Courses (and Enrollments for JOIN)

In [9]:
# Create Students table
c.execute('''
    CREATE TABLE Students (
        student_id INTEGER PRIMARY KEY,
        name TEXT NOT NULL,
        age INTEGER
    )
''')

# Create Courses table
c.execute('''
    CREATE TABLE Courses (
        course_id INTEGER PRIMARY KEY,
        course_name TEXT NOT NULL,
        instructor TEXT
    )
''')

# Create Enrollments table to link Students and Courses (for INNER JOIN requirement)
c.execute('''
    CREATE TABLE Enrollments (
        enrollment_id INTEGER PRIMARY KEY,
        student_id INTEGER,
        course_id INTEGER,
        FOREIGN KEY (student_id) REFERENCES Students(student_id),
        FOREIGN KEY (course_id) REFERENCES Courses(course_id)
    )
''')

conn.commit()
print("Tables Students, Courses, and Enrollments created successfully.")

Tables Students, Courses, and Enrollments created successfully.

### 2. Insert at least 5 records into each table

In [10]:
# Insert records into Students table
c.execute("INSERT INTO Students (name, age) VALUES ('Alice', 20)")
c.execute("INSERT INTO Students (name, age) VALUES ('Bob', 22)")
c.execute("INSERT INTO Students (name, age) VALUES ('Charlie', 21)")
c.execute("INSERT INTO Students (name, age) VALUES ('Diana', 23)")
c.execute("INSERT INTO Students (name, age) VALUES ('Eve', 20)")

# Insert records into Courses table
c.execute("INSERT INTO Courses (course_name, instructor) VALUES ('Math', 'Dr. Smith')")
c.execute("INSERT INTO Courses (course_name, instructor) VALUES ('Physics', 'Prof. Jones')")
c.execute("INSERT INTO Courses (course_name, instructor) VALUES ('Chemistry', 'Dr. Brown')")
c.execute("INSERT INTO Courses (course_name, instructor) VALUES ('History', 'Prof. Green')")
c.execute("INSERT INTO Courses (course_name, instructor) VALUES ('Literature', 'Dr. White')")

# Insert records into Enrollments table (linking students and courses)
c.execute("INSERT INTO Enrollments (student_id, course_id) VALUES (1, 1)") # Alice in Math
c.execute("INSERT INTO Enrollments (student_id, course_id) VALUES (1, 2)") # Alice in Physics
c.execute("INSERT INTO Enrollments (student_id, course_id) VALUES (2, 1)") # Bob in Math
c.execute("INSERT INTO Enrollments (student_id, course_id) VALUES (3, 3)") # Charlie in Chemistry
c.execute("INSERT INTO Enrollments (student_id, course_id) VALUES (4, 4)") # Diana in History
c.execute("INSERT INTO Enrollments (student_id, course_id) VALUES (5, 5)") # Eve in Literature
c.execute("INSERT INTO Enrollments (student_id, course_id) VALUES (2, 5)") # Bob in Literature

conn.commit()
print("Records inserted successfully into Students, Courses, and Enrollments tables.")

Records inserted successfully into Students, Courses, and Enrollments tables.

### 3. DDL Operations: ALTER TABLE

In [11]:
# Add a new column 'email' to the Students table
c.execute('''
    ALTER TABLE Students
    ADD COLUMN email TEXT
''')
conn.commit()
print("Column 'email' added to Students table.")

# Display the updated schema of Students table (optional check)
students_schema = pd.read_sql_query("PRAGMA table_info(Students)", conn)
display(students_schema)

Column 'email' added to Students table.

   cid        name     type  notnull dflt_value  pk
0    0  student_id  INTEGER        0       None   1
1    1        name     TEXT        1       None   0
2    2         age  INTEGER        0       None   0
3    3       email     TEXT        0       None   0

### 4. DML Operations: UPDATE and DELETE

In [12]:
# UPDATE: Update Alice's age and add an email
c.execute("UPDATE Students SET age = 21, email = 'alice@example.com' WHERE student_id = 1")
conn.commit()
print("Student record updated (Alice's age and email).")

# Display updated Students table
print("Students table after UPDATE:")
display(pd.read_sql_query("SELECT * FROM Students", conn))

# DELETE: Delete a course (e.g., Physics, which has course_id 2)
c.execute("DELETE FROM Courses WHERE course_id = 2")
conn.commit()
print("Course 'Physics' deleted from Courses table.")

# Display updated Courses table
print("Courses table after DELETE:")
display(pd.read_sql_query("SELECT * FROM Courses", conn))

# Note: Deleting a course that was enrolled in will leave orphaned entries in Enrollments
# For a robust system, CASCADE DELETE would be used, but for this example, we'll keep it simple.
# Let's also delete related enrollment for course_id 2 to clean up:
c.execute("DELETE FROM Enrollments WHERE course_id = 2")
conn.commit()
print("Related enrollments for course_id 2 also deleted.")

Student record updated (Alice's age and email).
Students table after UPDATE:

   student_id     name  age              email
0           1    Alice   21  alice@example.com
1           2      Bob   22               None
2           3  Charlie   21               None
3           4    Diana   23               None
4           5      Eve   20               None

Course 'Physics' deleted from Courses table.
Courses table after DELETE:

   course_id course_name   instructor
0          1        Math    Dr. Smith
1          3   Chemistry    Dr. Brown
2          4     History  Prof. Green
3          5  Literature    Dr. White

Related enrollments for course_id 2 also deleted.

### 5. SQL Queries: SELECT, WHERE, ORDER BY, GROUP BY, COUNT, AVG

In [13]:
# SELECT: Display all students
print("All Students:")
display(pd.read_sql_query("SELECT * FROM Students", conn))

# SELECT with WHERE: Students older than 20
print("Students older than 20:")
display(pd.read_sql_query("SELECT name, age FROM Students WHERE age > 20", conn))

# SELECT with ORDER BY: Courses ordered by name descending
print("Courses ordered by name (descending):")
display(pd.read_sql_query("SELECT course_name, instructor FROM Courses ORDER BY course_name DESC", conn))

# SELECT with GROUP BY and COUNT: Number of courses per instructor
print("Number of courses per instructor:")
display(pd.read_sql_query("SELECT instructor, COUNT(course_id) AS num_courses FROM Courses GROUP BY instructor", conn))

# SELECT with AVG: Average age of students
print("Average age of students:")
display(pd.read_sql_query("SELECT AVG(age) AS average_student_age FROM Students", conn))

All Students:

   student_id     name  age              email
0           1    Alice   21  alice@example.com
1           2      Bob   22               None
2           3  Charlie   21               None
3           4    Diana   23               None
4           5      Eve   20               None

Students older than 20:

      name  age
0    Alice   21
1      Bob   22
2  Charlie   21
3    Diana   23

Courses ordered by name (descending):

  course_name   instructor
0        Math    Dr. Smith
1  Literature    Dr. White
2     History  Prof. Green
3   Chemistry    Dr. Brown

Number of courses per instructor:

    instructor  num_courses
0    Dr. Brown            1
1    Dr. Smith            1
2    Dr. White            1
3  Prof. Green            1

Average age of students:

   average_student_age
0                 21.4

### 6. Perform an INNER JOIN between Students, Enrollments, and Courses

In [14]:
# INNER JOIN: Display students and the courses they are enrolled in
print("Students and their enrolled courses:")
display(pd.read_sql_query(
    """SELECT
        S.name AS StudentName,
        S.age AS StudentAge,
        C.course_name AS CourseName,
        C.instructor AS Instructor
    FROM
        Students AS S
    INNER JOIN
        Enrollments AS E ON S.student_id = E.student_id
    INNER JOIN
        Courses AS C ON E.course_id = C.course_id
    ORDER BY
        S.name, C.course_name
    """, conn
))

# Close the connection (important for saving if not in-memory, but good practice)
conn.close()
print("Database connection closed.")

Students and their enrolled courses:

  StudentName  StudentAge  CourseName   Instructor
0       Alice          21        Math    Dr. Smith
1         Bob          22  Literature    Dr. White
2         Bob          22        Math    Dr. Smith
3     Charlie          21   Chemistry    Dr. Brown
4       Diana          23     History  Prof. Green
5         Eve          20  Literature    Dr. White

Database connection closed.